
server:
  port: 8080

spring:
  application:
    name: image-upload-s3
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

aws:
  s3:
    credentials:
      access-key: your-access-key
      secret-key: your-secret-key
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: yourbucketname
