
server:
  port: 8080

spring:
  application:
    name: image-upload-filesystem
  datasource:
    url: jdbc:mysql://localhost:3306/imageDB
    username: root
    password: s3cret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


